# -*- coding: utf-8 -*-
"""surgeon project.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175vUOZ26RjHwK2JhcckZtINwnkZy6tLT
"""

!pip install -U transformers black autopep8 reportlab

return model_pipe
def detect_python_code(text):
    code_patterns = [r'def\s+\w+\s*\(', r'class\s+\w+', r'import\s+\w+', r'from\s+\w+\s+import', r'if\s+.:', r'for\s+.\s+in\s+', r'while\s+.*:']
    return any(re.search(pattern, text) for pattern in code_patterns)
def check_syntax(code):
    try:
        ast.parse(code)
        return True, None
    except SyntaxError as e:
        return False, f"Syntax Error (line {e.lineno}): {e.msg}"
    except Exception as e:
        return False, f"Error: {str(e)}"
def fix_code_indentation(code):
    lines = code.split('\n')
    fixed_lines = [line.rstrip().replace('\t', '    ') for line in lines]
    return '\n'.join(fixed_lines)

def fix_code_brackets(code):
    open_count = code.count('(') - code.count(')')
    if open_count > 0:
        code += ')' * open_count
    open_count = code.count('[') - code.count(']')
    if open_count > 0:
        code += ']' * open_count
    open_count = code.count('{') - code.count('}')
    if open_count > 0:
        code += '}' * open_count
    return code

def format_code(code):
    try:
        return black.format_str(code, mode=black.FileMode())
    except:
        try:
            return autopep8.fix_code(code)
        except:
            pass
def fix_python_code(code):
    code = fix_code_indentation(code)
    code = fix_code_brackets(code)
    is_valid, error_msg = check_syntax(code)
    if not is_valid:
        return {'success': False, 'fixed_code': code, 'error': error_msg, 'message': "Could not fully fix code: (error msg)"}
    code = format_code(code)
    return {'success': True, 'fixed_code': code, 'error': None, 'message': "Code fixed and formatted successfully!"}

def generate_response(user_message, temperature, max_tokens, top_p):
    conversation_history.append({"role": "user", "content": user_message})
    try:
        response = model_pipe(conversation_history, max_new_tokens=int(max_tokens), temperature=temperature, do_sample=True, top_p=top_p)
        assistant_message = response[0…
def process_user_input(user_message, temperature, max_tokens, top_p, chat_history):
    if not user_message.strip():
        return chat_history

    if detect_python_code(user_message):
        code_pattern = r"python\n(.?)\n\n(.)\n"
        code_match = re.search(code_pattern, user_message, re.DOTALL)
        if code_match:
            code_snippet = code_match.group(1) or code_match.group(2)
            fix_result = fix_python_code(code_snippet)
            if fix_result['success']:
                response_text = f"{fix_result['message']}\n\n*Fixed Code: *\npython\n{fix_result['fixed_code']}\n"
            else:
                response_text = f"{fix_result['message']}\n\n*Original Code:\npython\n{code_snippet}\n\n\n*Attempted Fix:\npython\n{fix_result['…
def clear_chat():
    global conversation_history
    conversation_history = []
    return []

def download_txt():
    if not conversation_history:
        return "X Chat is empty!", None

    content = f"Granite Chatbot - Complete Chat History\nExported: {datetime.now()}\n{'*'*80}\n\n"

    for i, msg in enumerate(conversation_history, 1):
        role = msg['role'].upper()
        content_text = msg['content']
        content += f"\n[Message {i}]\n{role}:\n{'-'*80}\n{content_text}\n{'-'*80}\n"

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"chat_history_{timestamp}.txt"

    try:
        Path(filename).write_text(content)
        return f"Downloaded: {filename}", filename
    except Exception as e:
        return f"X Error: {str(e)}", None
def download_pdf():
    if not conversation_history:
        return "Chat is empty", None

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"chat_history_{timestamp}.pdf"

    # Create a SimpleDocTemplate
    doc = SimpleDocTemplate(filename, pagesize=A4, topMargin=0.5*inch, bottomMargin=0.5*inch)
    styles = getSampleStyleSheet()
    story = []

    # Title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=28,
        textColor=0x333372,
        spaceAfter=12,
        alignment=1,
        fontName="Helvetica-Bold"
    )

    # User message style
    user_style = ParagraphStyle(
        'UserMessage',
        parent=styles['Normal'],
        fontSize=10,
        tex…
story.append(Paragraph(" Granite Chatbot Complete Chat History", title_style))
story.append(Paragraph(f"<b>Exported on:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
story.append(Paragraph(f"<b>Total Messages:</b> {len(conversation_history)}", styles['Normal']))
story.append(Spacer(1, 0.3*inch))

# Add each message
for i, msg in enumerate(conversation_history, 1):
    role = msg['role'].upper()
    content_text = msg['content']
    # Clean HTML characters
    clean_text = content_text.replace('<', '&lt;').replace('>', '&gt;')
    # Add message number
    story.append(Paragraph(f"<b>Message #{i}</b> <b style='color: #FF6B6B'>{role}</b>", styles['Normal']))
    # Add content with appropriate styling
    if msg['role'] == 'user':
     …
# Footer
story.append(Spacer(1, 0.3*inch))
story.append(Paragraph(f"<b>End of Chat History</b> | Generated by Granite Chatbot", styles['Normal']))

doc.build(story)
return f" Downloaded: {filename}", filename
except Exception as e:
return f"X Error: {str(e)}", None
def generate_share_link():
    if not conversation_history:
        return "X Chat is empty!"
    try:
        chat_content = ""
        for msg in conversation_history:
            role = msg['role'].upper()
            content = msg["content"]
            chat_content += f"({role}):\n{content}\n\n"
        pastebin_api = "https://pastebin.com/api/api_post.php"
        paste_data = {
            'api_dev_key': "",
            'api_option': 'paste',
            'api_paste_code': chat_content,
            'api_paste_name': f'Granite Chat ({datetime.now().strftime("%Y-%m-%d %H:%M")})',
            'api_paste_expire_date': '',
            'api_paste_private': '0'
        }
        response = requests.post(pastebin_api, data=paste_data, timeout=5)
        if 'pa…
load_model()

with gr.Blocks(title="Granite Chatbot", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# Granite Chatbot\n### Chat Python Code Fixer No API Keys")
    with gr.Row():
        with gr.Column(scale=3):
            chatbot = gr.Chatbot(label="Chat History", height=400, show_copy_button=True)
            with gr.Row():
                msg = gr.Textbox(label="Message", placeholder="Type message or paste Python code...", lines=2, scale=4)
                submit_btn = gr.Button("Send", scale=1, size="lg", variant="primary")
            with gr.Row():
                temperature = gr.Slider(label="Temp", minimum=0.1, maximum=1.0, value=0.7, step=0.05)
                max_tokens = gr.Slider(label="Tokens", minimum=50, maximum=1024, value=256, step=50)…

import re
import ast
import black
import autopep8
from datetime import datetime
from pathlib import Path
import requests

# For PDF generation
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
import gradio as gr # Assuming gradio is used based on the last block

conversation_history = []
# Assuming model_pipe is defined elsewhere or will be loaded by load_model()
model_pipe = None # Initialize model_pipe for now, assuming load_model will populate it

def detect_python_code(text):
    code_patterns = [r'def\s+\w+\s*\(', r'class\s+\w+', r'import\s+\w+', r'from\s+\w+\s+import', r'if\s+.:', r'for\s+.\s+in\s+', r'while\s+.*:']
    return any(re.search(pattern, text) for pattern in code_patterns)

def check_syntax(code):
    try:
        ast.parse(code)
        return True, None
    except SyntaxError as e:
        return False, f"Syntax Error (line {e.lineno}): {e.msg}"
    except Exception as e:
        return False, f"Error: {str(e)}"

def fix_code_indentation(code):
    lines = code.split('\n')
    fixed_lines = [line.rstrip().replace('\t', '    ') for line in lines]
    return '\n'.join(fixed_lines)

def fix_code_brackets(code):
    open_count = code.count('(') - code.count(')')
    if open_count > 0:
        code += ')' * open_count
    open_count = code.count('[') - code.count(']')
    if open_count > 0:
        code += ']' * open_count
    open_count = code.count('{') - code.count('}')
    if open_count > 0:
        code += '}' * open_count
    return code

def format_code(code):
    try:
        return black.format_str(code, mode=black.FileMode())
    except:
        try:
            return autopep8.fix_code(code)
        except:
            pass
    return code # Added return original code if formatting fails

def fix_python_code(code):
    code = fix_code_indentation(code)
    code = fix_code_brackets(code)
    is_valid, error_msg = check_syntax(code)
    if not is_valid:
        return {'success': False, 'fixed_code': code, 'error': error_msg, 'message': "Could not fully fix code: (error msg)"}
    code = format_code(code)
    return {'success': True, 'fixed_code': code, 'error': None, 'message': "Code fixed and formatted successfully!"}

def generate_response(user_message, temperature, max_tokens, top_p):
    global model_pipe
    if model_pipe is None:
        return "X Model not loaded. Please ensure `load_model()` is called and initializes `model_pipe`."

    conversation_history.append({"role": "user", "content": user_message})
    try:
        response = model_pipe(conversation_history, max_new_tokens=int(max_tokens), temperature=temperature, do_sample=True, top_p=top_p)
        # Fixed: Truncated code `response[0…`
        assistant_message = response[0]['generated_text']
        conversation_history.append({"role": "assistant", "content": assistant_message})
        return assistant_message
    except Exception as e:
        return f"X Error generating response: {str(e)}"

def process_user_input(user_message, temperature, max_tokens, top_p, chat_history):
    if not user_message.strip():
        return chat_history

    if detect_python_code(user_message):
        code_pattern = r"python\n(.?)\n\n(.)\n"
        code_match = re.search(code_pattern, user_message, re.DOTALL)
        if code_match:
            code_snippet = code_match.group(1) or code_match.group(2)
            fix_result = fix_python_code(code_snippet)
            if fix_result['success']:
                response_text = f"{fix_result['message']}\n\n*Fixed Code: *\npython\n{fix_result['fixed_code']}\n"
            else:
                # Fixed: Truncated code `fix_result['…`
                response_text = f"{fix_result['message']}\n\n*Original Code:\npython\n{code_snippet}\n\n\n*Attempted Fix:\npython\n{fix_result['fixed_code']}\n"
            chat_history.append((user_message, response_text))
            return chat_history
    # If not a code block or no code match, generate response normally
    response_from_model = generate_response(user_message, temperature, max_tokens, top_p)
    chat_history.append((user_message, response_from_model))
    return chat_history

def clear_chat():
    global conversation_history
    conversation_history = []
    return []

def download_txt():
    if not conversation_history:
        return "X Chat is empty!", None

    content = f"Granite Chatbot - Complete Chat History\nExported: {datetime.now()}\n{'*'*80}\n\n"

    for i, msg in enumerate(conversation_history, 1):
        role = msg['role'].upper()
        content_text = msg['content']
        content += f"\n[Message {i}]\n{role}:\n{'-'*80}\n{content_text}\n{'-'*80}\n"

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"chat_history_{timestamp}.txt"

    try:
        Path(filename).write_text(content)
        return f"Downloaded: {filename}", filename
    except Exception as e:
        return f"X Error: {str(e)}", None

def download_pdf():
    if not conversation_history:
        return "Chat is empty", None

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"chat_history_{timestamp}.pdf"

    # Create a SimpleDocTemplate
    doc = SimpleDocTemplate(filename, pagesize=A4, topMargin=0.5*inch, bottomMargin=0.5*inch)
    styles = getSampleStyleSheet()
    story = []

    # Title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=28,
        textColor=0x333372,
        spaceAfter=12,
        alignment=1,
        fontName="Helvetica-Bold"
    )

    # User message style
    user_style = ParagraphStyle(
        'UserMessage',
        parent=styles['Normal'],
        fontSize=10,
        # Fixed: Truncated code `tex…`
        textColor=0x000000
    )

    # Assistant message style (added for completeness)
    assistant_style = ParagraphStyle(
        'AssistantMessage',
        parent=styles['Normal'],
        fontSize=10,
        textColor=0x6B6B6B # A light grey for assistant
    )

    story.append(Paragraph(" Granite Chatbot Complete Chat History", title_style))
    story.append(Paragraph(f"<b>Exported on:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
    story.append(Paragraph(f"<b>Total Messages:</b> {len(conversation_history)}", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))

    # Add each message
    for i, msg in enumerate(conversation_history, 1):
        role = msg['role'].upper()
        content_text = msg['content']
        # Clean HTML characters
        clean_text = content_text.replace('<', '&lt;').replace('>', '&gt;')
        # Add message number
        story.append(Paragraph(f"<b>Message #{i}</b> <b style='color: #FF6B6B'>{role}</b>", styles['Normal']))
        # Add content with appropriate styling
        if msg['role'] == 'user':
            # Fixed: Truncated code `if msg['role'] == 'user': ...`
            story.append(Paragraph(clean_text, user_style))
        else:
            story.append(Paragraph(clean_text, assistant_style))
        story.append(Spacer(1, 0.1*inch)) # Small spacer between messages

    # Footer
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph(f"<b>End of Chat History</b> | Generated by Granite Chatbot", styles['Normal']))

    try:
        doc.build(story)
        return f" Downloaded: {filename}", filename
    except Exception as e:
        return f"X Error: {str(e)}", None

def generate_share_link():
    if not conversation_history:
        return "X Chat is empty!"
    try:
        chat_content = ""
        for msg in conversation_history:
            role = msg['role'].upper()
            content = msg["content"]
            chat_content += f"({role}):\n{content}\n\n"
        pastebin_api = "https://pastebin.com/api/api_post.php"
        paste_data = {
            'api_dev_key': "", # Placeholder, typically requires an actual API key
            'api_option': 'paste',
            'api_paste_code': chat_content,
            'api_paste_name': f'Granite Chat ({datetime.now().strftime("%Y-%m-%d %H:%M")})',
            'api_paste_expire_date': '',
            'api_paste_private': '0'
        }
        response = requests.post(pastebin_api, data=paste_data, timeout=5)
        # Fixed: Truncated code `if 'pa…`
        if 'pastebin.com' in response.text: # Assuming successful paste returns the URL
            return f"Share Link: {response.text}"
        else:
            return f"X Error creating share link: {response.text}"
    except Exception as e:
        return f"X Error generating share link: {str(e)}"

def load_model():
    # Placeholder for model loading. User needs to implement this.
    # Example: Hogan (LLM)
    # from transformers import pipeline
    global model_pipe
    # model_pipe = pipeline("text-generation", model="HuggingFaceH4/zephyr-7b-beta")
    # For demonstration without an actual model, let's set a dummy function
    def dummy_pipeline(history, **kwargs):
        last_user_message = history[-1]['content']
        return [{'generated_text': f"Hello, I received your message: {last_user_message}. This is a dummy response."}]
    model_pipe = dummy_pipeline

load_model()

with gr.Blocks(title="Granite Chatbot", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# Granite Chatbot\n### Chat Python Code Fixer No API Keys")
    with gr.Row():
        with gr.Column(scale=3):
            chatbot = gr.Chatbot(label="Chat History", height=400, show_copy_button=True)
            with gr.Row():
                msg = gr.Textbox(label="Message", placeholder="Type message or paste Python code...", lines=2, scale=4)
                submit_btn = gr.Button("Send", scale=1, size="lg", variant="primary")
            with gr.Row():
                temperature = gr.Slider(label="Temp", minimum=0.1, maximum=1.0, value=0.7, step=0.05)
                max_tokens = gr.Slider(label="Tokens", minimum=50, maximum=1024, value=256, step=50)
                # Fixed: Truncated code `max_tokens = gr.Slider(... step=50)…`
                top_p = gr.Slider(label="Top P", minimum=0.1, maximum=1.0, value=0.9, step=0.05) # Added missing top_p slider
            with gr.Row(): # Added a new row for action buttons
                clear_btn = gr.Button("Clear Chat")
                download_txt_btn = gr.Button("Download Chat (.txt)")
                download_pdf_btn = gr.Button("Download Chat (.pdf)")
                share_btn = gr.Button("Share Chat")

            submit_btn.click(process_user_input, inputs=[msg, temperature, max_tokens, top_p, chatbot], outputs=chatbot)
            clear_btn.click(clear_chat, outputs=chatbot)
            download_txt_btn.click(download_txt, outputs=gr.File())
            download_pdf_btn.click(download_pdf, outputs=gr.File())
            share_btn.click(generate_share_link, outputs=gr.Textbox())

demo.launch(debug=True)